### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by aditi48n** [UBC-MDS/DSCI522-Group16-2022#42]
Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work! 

Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

- [ ] Could not reproducibly run the analysis because no computational environment/dependencies was provided. -5 reasoning
- [ ] Command line arguments are missing for final report generation.  -1 accuracy
- [ ] The proposal.md file has not been created and moved to the doc directory -2 mechanics
- [ ]  Plots suffer from one or more severe problems. For instance, overplotting, missing legend, small text or no axis labels. -1 viz
**Comment:** The text in the plots and tables is very small and hard to read in the final rendered HTML. 
- [ ] Challenging question- Tests arent present for any of the scripts. -7
