### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by muntakimrafi** [UBC-MDS/DSCI522-Group16-2022#9]
_Congratulations on finishing milestone 1!
Below I list some specific feedback you can use to improve your project.
I provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread._

**Project proposal**

- [x] Make a separate header titled Contributors and Maintainers and put contributors there. The way you are describing the project, a separate project proposal title is not needed. 

**A script that downloads and saves the data**

- [ ] The script is placed in an appropiated subdirectory as the src folder -1
- [ ]  A first copy of the data must be saved in the data directory (and ideally in the data/raw subdirectory. -1

**Exploratory data analysis in a literate code document**

- [ ] There are not figure captions. -2 
- [ ] Narration of methods and method choices was not as clear and thorough as expected. -1
- [ ] Usage documentation is missing. -2
- [ ] Dependencies is missing from the README.md file. -2
